### ISSUE TITLE
AVHRR data missing between 5/2003 and 11/2003

### ISSUE THREAD

**Issue by oembury** [surftemp/sst-cci#5]
Appears to be a failure in the l1c pre-processing

**Comment by cbulgin** [comment]
This is not an L1C problem but an issue with the L1b reader.  The missing data in the L1C record occur where their is no archive header in the L1b file - this causes the L1b reader to raise an error and stop processing.

**Comment by oembury** [comment]
Version 1.2 of L1C includes missing files
